# Generated by Django 5.0.2 on 2024-07-30 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_pagamento_data_pagamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagamento',
            name='valor',
            field=models.CharField(choices=[('9.90', 'R$ 9,90'), ('19.90', 'R$ 19,90'), ('47.75', 'R$ 47,75')], max_length=10),
        ),
    ]
