# Generated by Django 5.0.2 on 2024-07-30 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_pagamento_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagamento',
            name='meio_pagamento',
            field=models.CharField(default=('pix', 'cartao_de_credito', 'boleto'), max_length=255),
            preserve_default=False,
        ),
    ]
